version: '3.1'
services:

    webserver:
        image: php:8.0.3-apache
        container_name: uhctf_studentportal
        restart: always
        volumes:
            - ./src/:/var/www/html/
        ports:
            - 80:80
